source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
gem "minimal-mistakes-jekyll"
gem "jekyll-include-cache"
gem "webrick" # Required for Ruby 3.x+
gem "csv" # Required for Ruby 3.4+
gem "base64" # Required for Ruby 3.4+
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]



group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-gist"
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jemoji"
  gem "jekyll-remote-theme"
end
